### ISSUE TITLE
Review DSS deleting operations

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/SaveLifecycleRecordsPlugin#1]
@ktarbet please review the code in SaveLifecycleRecordsPlugin/src/savelifecyclerecordsplugin/SaveLifecycleRecordsAlternative.java
the compute() method. Specifically the portion where I collect all dss pathnames, iterate through them to find matches and then perform a mass delete of unmatched records.

I think this should be the proper way, but I would like some review before I test it on real data.

**Comment by ktarbet** [comment]
Thanks for walking me through the code.   It looks good to me.   
I usually look for a zero (OK) status in DSS methods, so you may wish to use:
0 != DssFileManagerImpl.getDssFileManager(...
instead of 
0>DssFileManagerImpl.getDssFileManager(...

However, in this case the return values is in (0,-1, or -2)  where zero is OK, so the code is fine.
